### PR TITLE
Add Function BlorfAntiCheat

### PR DESCRIPTION
**Pull request by isKoi**
对方将看到假牌，丢出去的牌仍然是真的，这点无法做出改变，理论上没什么用(doge)

### CODE REVIEW

**Comment by dogdie233** [comment]
加点注释在你的修改上？
感觉你这里挺多的内容都是官方原本的逻辑，给你的修改加上注释，表示你修改之后的逻辑可能更好

**Review by dogdie233 — CHANGES_REQUESTED** [review]
给你改的逻辑加点注释（？
至少注释一下你的逻辑更改在什么地方了

**Comment by AshAmetrine** [comment]
This only prevents the person with the patch from cheating. 
There's no server side verification, so random people who join your lobby would still be able to cheat.

**Review by dogdie233 — APPROVED** [review]

**Comment by dogdie233** [comment]
> This only prevents the person with the patch from cheating. There's no server side verification, so random people who join your lobby would still be able to cheat.

Haha, if you decompile the code of the game, you will see nearly __ALL__ logic running on client-side

**Comment by AshAmetrine** [comment]
> > This only prevents the person with the patch from cheating. There's no server side verification, so random people who join your lobby would still be able to cheat.
> 
> Haha, if you decompile the code of the game, you will see nearly **ALL** logic running on client-side

which is why it's so easy to cheat.

**Pull request merged**
